### ISSUE TITLE
Code Refactoring and Structure Improvement 

### ISSUE THREAD

**Issue by Abhisheksingh734** [rizkytegar/indonesian-digital-clock#12]
Hey,
I've created this issue to suggest a code refactoring and structural improvement for this project.

## Proposed changes

* splitting the existing code in the App.js file into separate components.
```
src/
├── components/
│   ├── DigitalClock.js
│   ├── TimeZoneSelector.js
├── App.js
```

### Components folder:
* DigitalClock.js: This file contains the code for the Digital Clock component.
* TimeZoneSelector.js: This file contains the code for the time zone selector component.

Please let me know whether I should proceed with implementing these changes or you have any different idea.
Thank You!

**Comment by rizkytegar** [comment]
It's very interesting, it can be made and then become PR

**Comment by KathanrDave** [comment]
hey! @rizkytegar I have made a PR for the issue.

**Comment by rizkytegar** [comment]
hello, has @Abhisheksingh734 resolved this case?

I have to check first whether @Abhisheksingh734 is still continuing this problem, if not I will review and try to revise the PR from @KathanrDave

**Comment by Abhisheksingh734** [comment]
Hii @rizkytegar, 
I wasn't actively working on this issue. Therefore, please feel free to proceed with merging the PR whenever you see fit. 😊
